module.exports = {
    tutorialSidebar: [
        'about-lionweb',
        'resources',
        {
          type: 'category',
          label: 'About this project',
          items: [{ type: 'autogenerated', dirName: 'About this project' }],
        },
        {
          type: 'category',
          label: 'Introduction',
          items: [{ type: 'autogenerated', dirName: 'Introduction' }],
        },
        {
          type: 'category',
          label: 'LionWeb Java',
          items: [{ type: 'autogenerated', dirName: 'Guides-Java' }],
        },
        {
          type: 'category',
          label: 'LionWeb Kotlin',
          items: [{ type: 'autogenerated', dirName: 'Guides-Kotlin' }],
        },
        {
          type: 'category',
          label: 'LionWeb Python',
          items: [{ type: 'autogenerated', dirName: 'Guides-Python' }],
        },
        {
          type: 'category',
          label: 'LionWeb Typescript',
          items: [{ type: 'autogenerated', dirName: 'Guides-Typescript' }],
        },
        {
          type: 'category',
          label: 'LionWeb C#',
          items: [{ type: 'autogenerated', dirName: 'Guides-Csharp' }],
        },
        {
          type: 'category',
          label: 'LionWeb Repository',
          items: [{ type: 'autogenerated', dirName: 'Guides-Repository' }],
        },
    ],
  };